const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs')
const {launchApp}=require('../zernio/support/electron-app.cjs')
test('imported YouTube cookies survive an app restart',{timeout:90000},async t=>{
 const root=path.resolve('.pytest_cache','youtube-ui-'+Date.now())
 const {app,page,close}=await launchApp({appDir:path.resolve('.'),userDataDir:root});t.after(close)
 const fixture=path.join(root,'cookies.txt')
 fs.writeFileSync(fixture,'# Netscape HTTP Cookie File\n.youtube.com\tTRUE\t/\tTRUE\t2000000000\tSID\timported-fixture-secret\n')
 await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]})},fixture)
 assert.equal(await page.evaluate(()=>window.bridgeclip.youtube.importCookies()),true)
 assert.ok(!fs.readFileSync(path.join(root,'youtube-session.enc')).includes(Buffer.from('imported-fixture-secret')))
 const imported=await app.evaluate(({app,safeStorage})=>JSON.parse(safeStorage.decryptString(process.getBuiltinModule('fs').readFileSync(process.getBuiltinModule('path').join(app.getPath('userData'),'youtube-session.enc')))))
 assert.equal(imported.cookies[0].value,'imported-fixture-secret')
 assert.equal(fs.existsSync(fixture),true)
 await page.evaluate(async()=>{await window.bridgeclip.youtube.pasteCookies(JSON.stringify([{domain:'.youtube.com',expirationDate:2000000000.123,hostOnly:false,httpOnly:true,name:'SID',path:'/',sameSite:'unspecified',secure:true,session:false,storeId:'0',value:'pasted-fixture-value',id:1}]))})
 const pasted=await app.evaluate(({app,safeStorage})=>JSON.parse(safeStorage.decryptString(process.getBuiltinModule('fs').readFileSync(process.getBuiltinModule('path').join(app.getPath('userData'),'youtube-session.enc')))))
 assert.equal(pasted.cookies[0].value,'pasted-fixture-value')
 assert.ok(!fs.readFileSync(path.join(root,'youtube-session.enc')).includes(Buffer.from('pasted-fixture-value')))
 await close()
 const restarted=await launchApp({appDir:path.resolve('.'),userDataDir:root});t.after(restarted.close)
 const restored=await restarted.app.evaluate(({app,safeStorage})=>JSON.parse(safeStorage.decryptString(process.getBuiltinModule('fs').readFileSync(process.getBuiltinModule('path').join(app.getPath('userData'),'youtube-session.enc')))))
 assert.equal(restored.cookies[0].value,'pasted-fixture-value')
 assert.equal(await restarted.app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().length),1)

})
